# Generated by Django 2.1 on 2019-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('size', models.BigIntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('maturity', models.DateField()),
                ('lei', models.CharField(max_length=20)),
                ('legal_name', models.CharField(max_length=50)),
            ],
        ),
    ]
